## Install Python using pyenv.
##
- name: install pyenv
  block:
    
    - name: download installer
      get_url:
        url: https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer
        dest: "{{ python3_tmpdir }}"

    - name: run installer
      command: "bash pyenv-installer"
      args:
        chdir: "{{ python3_tmpdir }}"
        
    - name: update login file
      blockinfile:
        path: "{{ python3_shellrc }}"
        create: true
        block: |
          export PATH="{{ ansible_user_dir }}/.pyenv/bin:$PATH"
          eval "$(pyenv init -)"
          eval "$(pyenv virtualenv-init -)"
      
    - name: update pyenv
      command: pyenv update
      environment:
        PATH: "{{ ansible_env.PATH }}:{{ ansible_user_dir }}/.pyenv/bin"


- meta: end_play

# FIXME: Broken for CentOS and Ubuntu; need additional libraries
- name: install Python
  command: "pyenv install {{ python3_pyenv }}"
