## Tasks unique to Ubuntu.
##
- name: requirements for Python install
  block:

    - name: install repositories
      become: true
      apt_repository:
        repo: "{{ item }}"
        update_cache: true
      with_items:
        - ppa:deadsnakes/ppa

    - name: install system packages
      become: true
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - python3.6

    - name: download pip installer
      get_url:
        url: https://bootstrap.pypa.io/get-pip.py
        dest: "{{ python3_tmpdir }}/"

    - name: install pip
      become: true
      command: "{{ python3_command }} get-pip.py"
      args:
        chdir: "{{ python3_tmpdir }}/"
 
  when: python3_pyenv == None


- name: requirements for pyenv install
  block:

    - name: set system facts
      set_fact:
        python3_profile: ~/.profile
      
    - name: install system packages
      become: true
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - git

  when: python3_pyenv != None
