## Tasks unique to Ubuntu.
##
- name: requirements for package install
  block:

    - name: install repositories
      become: true
      apt_repository:
        repo: "{{ item }}"
        update_cache: true
      with_items:
        - ppa:deadsnakes/ppa

    - name: install Python system packages
      become: true
      apt:
        name:
          - python3.6
          - python3.6-dev
          - python3.6-venv  # installs ensurepip module but not pip itself
        state: present

    - name: set system facts
      set_fact:
        python3_command: python3.6

    - name: install pip
      become: true
      command: "{{ python3_command }} -m ensurepip"

    - name: install Python packages
      become: true
      pip:
        name:
          - virtualenv
        state: present
        executable: pip3
      when: python3_pyenv == None

  when: python3_pyenv == None and ansible_distribution_major_version == "14"


- name: install Python utilities
  become: true
  apt:
    name:
      - python3-pip
      - python3-virtualenv
      - python3-dev
      - virtualenv
  when: python3_pyenv == None and ansible_distribution_major_version != "14"


- name: requirements for pyenv install
  block:
    - name: install system packages required for pyenv
      apt:
        name:
          - curl
          - gcc
          - git
          - libbz2-dev
          - libreadline-dev
          - libssl-dev
          - libsqlite3-dev
          - make
          - zlib1g-dev
        state: present
  become: true
  when: python3_pyenv != None
