## Tasks unique to Ubuntu.
##
- name: requirements for package install
  block:

    - name: install repositories
      become: true
      apt_repository:
        repo: "{{ item }}"
        update_cache: true
      with_items:
        - ppa:deadsnakes/ppa

    - name: install Python system packages
      become: true
      apt:
        name:
          - python3.6
          - python3.6-dev
          - python3.6-venv  # installs ensurepip module but not pip itself
        state: present

    - name: install pip
      become: true
      command: "{{ python3_command }} -m ensurepip"

  when: python3_pyenv == None


- name: requirements for pyenv install
  block:

    - name: install system packages required for pyenv
      become: true
      apt:
        name:
          - curl
          - gcc
          - git
          - libbz2-dev
          - libreadline-dev
          - libssl-dev
          - libsqlite3-dev
          - make
          - zlib1g-dev
        state: present

  when: python3_pyenv != None
